const puppeteer = require('puppeteer');
const { parentPort } = require('worker_threads');

const urlsToScrape = [
  'https://www.ebag.bg/categories/zanaiatchiiski-khliab-s-kvas/1512',
  'https://www.ebag.bg/categories/bageti-chiabati-i-burger-pitki/1513',
  'https://www.ebag.bg/categories/zakuski/1514',
  'https://www.ebag.bg/categories/khliab-pekarna/1569',
  'https://www.ebag.bg/categories/khliab/479',
  'https://www.ebag.bg/categories/proteinov-i-keto-khliab/1959',
  'https://www.ebag.bg/categories/plnozrnest-khliab/1960',
  'https://www.ebag.bg/categories/khliab-s-kvas/1961',
  'https://www.ebag.bg/categories/sukhari/1861',
  'https://www.ebag.bg/categories/kroasani/316',
  'https://www.ebag.bg/categories/keksove-i-rula/485',
  'https://www.ebag.bg/categories/brauni-i-mfini/1857',
  'https://www.ebag.bg/categories/sukhi-pasti-i-sladkishi/1859',
  'https://www.ebag.bg/categories/drebni-sladki-i-kurabii/1858',
  'https://www.ebag.bg/categories/blat-za-torta-i-bishkoti/878',
  'https://www.ebag.bg/categories/bezglutenov-khliab/1864',
  'https://www.ebag.bg/categories/bezglutenovi-bageti-i-pitki/1865',
  'https://www.ebag.bg/categories/bezglutenovi-zakuski/1867',
  'https://www.ebag.bg/categories/bezglutenovi-bishkoti/1868',
  'https://www.ebag.bg/categories/torti/1874',
  'https://www.ebag.bg/categories/ekleri-i-profiteroli/1876',
  'https://www.ebag.bg/categories/brauni-keksove-i-sladkishi/1877',
  'https://www.ebag.bg/categories/baklavi-tulumbi-i-siropirani-sladkishi/1878',
  'https://www.ebag.bg/categories/brashno/393',
  'https://www.ebag.bg/categories/smesi-za-khliab/1870',
  'https://www.ebag.bg/categories/zakhar/794',
  'https://www.ebag.bg/categories/desertni-kremove/403',
  'https://www.ebag.bg/categories/desertni-smesi/1871',
  'https://www.ebag.bg/categories/desertni-podpravki/793',
  'https://www.ebag.bg/categories/panirovki/1872',
  'https://www.ebag.bg/categories/aksesoari-za-domashna-pekarna/2349',
  'https://www.ebag.bg/categories/tocheni-kori/1923',
  'https://www.ebag.bg/categories/testo/1924',
  'https://www.ebag.bg/categories/khliab-pitki-bageti-i-brettseli/1941',
  'https://www.ebag.bg/categories/testo-i-blatove/1942',
  'https://www.ebag.bg/categories/banitsi-i-zakuski/1943',
  'https://www.ebag.bg/categories/kroasani-i-palachinki/1944',
  'https://www.ebag.bg/categories/sladkishi-torti-i-donti/1945',
  'https://www.ebag.bg/categories/pitsi-i-pide/1946',
  'https://www.ebag.bg/categories/banani-i-ekzotichni-plodove/1466',
  'https://www.ebag.bg/categories/iablki-i-krushi/1468',
  'https://www.ebag.bg/categories/iagodi-i-gorski-plodove/1471',
  'https://www.ebag.bg/categories/praskovi-nektarini-i-slivi/1470',
  'https://www.ebag.bg/categories/tsitrusi/1469',
  'https://www.ebag.bg/categories/dinia-ppesh-i-grozde/1467',
  'https://www.ebag.bg/categories/tikva-ppesh-dinia/1507',
  'https://www.ebag.bg/categories/akesoari-za-plodove/2350',
  'https://www.ebag.bg/categories/domati-novo/2840',
  'https://www.ebag.bg/categories/krastavitsi-asperzhi-artishok/1508',
  'https://www.ebag.bg/categories/chushka/2851',
  'https://www.ebag.bg/categories/krastavitsi-tikvichki-patladzhani/1456',
  'https://www.ebag.bg/categories/karfiol-zele/1462',
  'https://www.ebag.bg/categories/drugi/1465',
  'https://www.ebag.bg/categories/aksesoari-za-zelenchutsi/2351',
  'https://www.ebag.bg/categories/kartof/2862',
  'https://www.ebag.bg/categories/morkovi-i-korenoplodni-zelenchutsi/1457',
  'https://www.ebag.bg/categories/luk-chesn-i-praz/1458',
  'https://www.ebag.bg/categories/riapa-tsveklo-i-tselina/2860',
  'https://www.ebag.bg/categories/drugi-korenoplodni/2861',
  'https://www.ebag.bg/categories/svezhi-salati-repichki-i-aisberg/2866',
  'https://www.ebag.bg/categories/spanak-i-zelenolistni/2867',
  'https://www.ebag.bg/categories/praz-presen-luk-i-chesn/2868',
  'https://www.ebag.bg/categories/svezhi-salati/773',
  'https://www.ebag.bg/categories/presni-turshii/2145',
  'https://www.ebag.bg/categories/aksesoari-za-salati/2352',
  'https://www.ebag.bg/categories/gbi/1473',
  'https://www.ebag.bg/categories/susheni-gbi/1803',
  'https://www.ebag.bg/categories/klnove/1150',
  'https://www.ebag.bg/categories/klnove-i-mikrorasteniia/1515',
  'https://www.ebag.bg/categories/ekzotichni-plodove/1583',
  'https://www.ebag.bg/categories/ekzotichni-zelenchutsi/1582',
  'https://www.ebag.bg/categories/bio-plodove/1472',
  'https://www.ebag.bg/categories/bio-zelenchutsi/1464',
  'https://www.ebag.bg/categories/paketirani-surovi-iadki/1791',
  'https://www.ebag.bg/categories/paketirani-surovi-iadki-miks/1792',
  'https://www.ebag.bg/categories/nasipni-surovi-iadki/1796',
  'https://www.ebag.bg/categories/nasipni-surovi-iadki-miks/1797',
  'https://www.ebag.bg/categories/paketirani-pecheni-iadki/1789',
  'https://www.ebag.bg/categories/paketirani-pecheni-iadki-miks/1790',
  'https://www.ebag.bg/categories/nasipni-pecheni-iadki/1795',
  'https://www.ebag.bg/categories/paketirani-susheni-plodove/1793',
  'https://www.ebag.bg/categories/paketirani-susheni-zelenchutsi/1794',
  'https://www.ebag.bg/categories/nasipni-susheni-plodove/1798',
  'https://www.ebag.bg/categories/div-ulov/1518',
  'https://www.ebag.bg/categories/fileta/1516',
  'https://www.ebag.bg/categories/tseli-ribi/1517',
  'https://www.ebag.bg/categories/kotleti/1520',
  'https://www.ebag.bg/categories/morski-darove/1519',
  'https://www.ebag.bg/categories/tsialo-pile/1708',
  'https://www.ebag.bg/categories/file-przholi-i-shishcheta/1709',
  'https://www.ebag.bg/categories/butcheta-i-krila/1710',
  'https://www.ebag.bg/categories/marinovano-pileshko-meso/2284',
  'https://www.ebag.bg/categories/pileshki-subprodukti/1711',
  'https://www.ebag.bg/categories/panirani-pileshki-produkti/1712',
  'https://www.ebag.bg/categories/tseli-parcheta-mesa/1713',
  'https://www.ebag.bg/categories/przholi-shishcheta-rebra-i-nariazano-meso/1714',
  'https://www.ebag.bg/categories/zrialo-svinsko-meso/1715',
  'https://www.ebag.bg/categories/marinovano-svinsko-meso/1986',
  'https://www.ebag.bg/categories/slanina-i-svinska-mas/1716',
  'https://www.ebag.bg/categories/svinski-subprodukti/1717',
  'https://www.ebag.bg/categories/tseli-parcheta-meso/1718',
  'https://www.ebag.bg/categories/stekove-shishcheta-rebra-i-nariazano-meso/1719',
  'https://www.ebag.bg/categories/zreli-govezhdi-mesa/1720',
  'https://www.ebag.bg/categories/bio-teleshko-meso/1721',
  'https://www.ebag.bg/categories/govezhdi-subprodukti/1722',
  'https://www.ebag.bg/categories/svinska-kaima/1723',
  'https://www.ebag.bg/categories/teleshka-i-govezhda-kaima/1724',
  'https://www.ebag.bg/categories/kaima-smes/1725',
  'https://www.ebag.bg/categories/pueshka-kaima/1726',
  'https://www.ebag.bg/categories/kiufteta-novo/2329',
  'https://www.ebag.bg/categories/kebapcheta/1490',
  'https://www.ebag.bg/categories/pleskavitsi-kltsanitsi-i-burgeri/1492',
  'https://www.ebag.bg/categories/nadenitsa/1491',
  'https://www.ebag.bg/categories/svinsko-meso/1727',
  'https://www.ebag.bg/categories/pileshko-meso/1728',
  'https://www.ebag.bg/categories/teleshko-meso/1729',
  'https://www.ebag.bg/categories/pateshko-zaeshko-i-agneshko-meso/1730',
  'https://www.ebag.bg/categories/morski-darove/1731',
  'https://www.ebag.bg/categories/zelenchutsi/1735',
  'https://www.ebag.bg/categories/pushena-riba/417',
  'https://www.ebag.bg/categories/marinovana-riba/1552',
  'https://www.ebag.bg/categories/ribni-delikatesi/416',
  'https://www.ebag.bg/categories/haiver/414',
  'https://www.ebag.bg/categories/tarama-khaiveri/1563',
  'https://www.ebag.bg/categories/presni-iaitsa/1745',
  'https://www.ebag.bg/categories/bio-presni-iaitsa/1746',
  'https://www.ebag.bg/categories/pastorizirani-iaitsa/1747',
  'https://www.ebag.bg/categories/priasno-mliako/1608',
  'https://www.ebag.bg/categories/uht-priasno-mliako/1609',
  'https://www.ebag.bg/categories/kondenzirano-mliako/1610',
  'https://www.ebag.bg/categories/bio-priasno-mliako/1611',
  'https://www.ebag.bg/categories/priasno-mliako-bez-laktoza/1612',
  'https://www.ebag.bg/categories/krave-mliako/1602',
  'https://www.ebag.bg/categories/ovche-koze-i-bivolsko-mliako/1603',
  'https://www.ebag.bg/categories/tsedeno-mliako/1604',
  'https://www.ebag.bg/categories/bio-mliako/1605',
  'https://www.ebag.bg/categories/mliako-bez-laktoza/1606',
  'https://www.ebag.bg/categories/krave-sirene/1833',
  'https://www.ebag.bg/categories/ovche-koze-i-bivolsko-sirene/1834',
  'https://www.ebag.bg/categories/vnosni-salamureni-sirena/1855',
  'https://www.ebag.bg/categories/sirene-bez-laktoza/1835',
  'https://www.ebag.bg/categories/niskomasleo-sirene/1836',
  'https://www.ebag.bg/categories/sirene-za-gril-i-skara/1837',
  'https://www.ebag.bg/categories/feta-sirene/1838',
  'https://www.ebag.bg/categories/bio-sirene/1839',
  'https://www.ebag.bg/categories/parmezan-i-drugi-tvrdi-sirena/1815',
  'https://www.ebag.bg/categories/gauda-emental-i-drugi-polutvrdi-sirena/1816',
  'https://www.ebag.bg/categories/bri-kamember-i-drugi-meki-sirena/1817',
  'https://www.ebag.bg/categories/sino-sirene/1818',
  'https://www.ebag.bg/categories/nastrgani-sirena/1819',
  'https://www.ebag.bg/categories/aksesoari-za-delikatesni-sirena/2355',
  'https://www.ebag.bg/categories/krema-sirene/1821',
  'https://www.ebag.bg/categories/topeno-sirene/1822',
  'https://www.ebag.bg/categories/motsarela-burata-i-rikota/1823',
  'https://www.ebag.bg/categories/kotidzh/1824',
  'https://www.ebag.bg/categories/maskarpone/1825',
  'https://www.ebag.bg/categories/izvara/1826',
  'https://www.ebag.bg/categories/labne/1827',
  'https://www.ebag.bg/categories/kashkaval-ot-krave-mliako/1806',
  'https://www.ebag.bg/categories/kashkaval-ot-ovche-koze-i-bivolsko-mliako/1807',
  'https://www.ebag.bg/categories/kashkaval-bez-laktoza/1808',
  'https://www.ebag.bg/categories/niskomaslen-kashkaval/1809',
  'https://www.ebag.bg/categories/kashkaval-s-podpravki-i-kashkavaleno-role/1810',
  'https://www.ebag.bg/categories/nastrgan-kashkaval/1811',
  'https://www.ebag.bg/categories/bio-kashkaval/1812',
  'https://www.ebag.bg/categories/giubek/1813',
  'https://www.ebag.bg/categories/maslo/378',
  'https://www.ebag.bg/categories/maslo-bez-sol/1937',
  'https://www.ebag.bg/categories/bio-maslo/1938',
  'https://www.ebag.bg/categories/gkhi/1939',
  'https://www.ebag.bg/categories/zakvasena-smetana/1696',
  'https://www.ebag.bg/categories/smetana-za-gotvene/1697',
  'https://www.ebag.bg/categories/sladkarska-smetana/1698',
  'https://www.ebag.bg/categories/produkti-za-mazane/1553',
  'https://www.ebag.bg/categories/salati/1829',
  'https://www.ebag.bg/categories/salati-bez-konservanti/2101',
  'https://www.ebag.bg/categories/raziadki-i-antipasti/1830',
  'https://www.ebag.bg/categories/katk/1831',
  'https://www.ebag.bg/categories/khumus/1832',
  'https://www.ebag.bg/categories/khumus-bez-konservanti/2102',
  'https://www.ebag.bg/categories/priasna-pasta/1588',
  'https://www.ebag.bg/categories/svezhi-sosove/1589',
  'https://www.ebag.bg/categories/gotovi-khrani/1585',
  'https://www.ebag.bg/categories/sandvichi/1586',
  'https://www.ebag.bg/categories/aziatska-kukhnia/1560',
  'https://www.ebag.bg/categories/supi/2023',
  'https://www.ebag.bg/categories/plodovi-mleka/1933',
  'https://www.ebag.bg/categories/ovkuseni-mlechni-napitki/1934',
  'https://www.ebag.bg/categories/mlechni-deserti-i-puding/1935',
  'https://www.ebag.bg/categories/deserti/1875',
  'https://www.ebag.bg/categories/skir-i-kvark/1936',
  'https://www.ebag.bg/categories/airian/386',
  'https://www.ebag.bg/categories/boza/746',
  'https://www.ebag.bg/categories/vegan-mleka/1739',
  'https://www.ebag.bg/categories/vegan-sirena/1740',
  'https://www.ebag.bg/categories/podkvaseni-vegan-produkti-i-deserti/1741',
  'https://www.ebag.bg/categories/vegan-masla/1742',
  'https://www.ebag.bg/categories/vegan-smetana/1743',
  'https://www.ebag.bg/categories/krenvirshi-i-malotraini-kolbasi/2017',
  'https://www.ebag.bg/categories/lukanki-i-sudzhutsi/2018',
  'https://www.ebag.bg/categories/shpekovi-i-lukankovi-salami/2019',
  'https://www.ebag.bg/categories/shunka-bekon-i-fileta/2020',
  'https://www.ebag.bg/categories/surovo-susheni-mesa-i-pastrmi/2021',
  'https://www.ebag.bg/categories/sazdrmi/2022',
  'https://www.ebag.bg/categories/lukanki-sudzhutsi-i-drugi/1842',
  'https://www.ebag.bg/categories/salami-i-lukankovi-kolbasi/1843',
  'https://www.ebag.bg/categories/vnosni-salami/1844',
  'https://www.ebag.bg/categories/surovo-susheni-mesa/1845',
  'https://www.ebag.bg/categories/vareno-pusheni-mesa-i-mortadela/1846',
  'https://www.ebag.bg/categories/miks-kolbasi/1847',
  'https://www.ebag.bg/categories/teleshki-khamburgski-i-kamchiia/1749',
  'https://www.ebag.bg/categories/krenvirshi/1751',
  'https://www.ebag.bg/categories/mortadela/1752',
  'https://www.ebag.bg/categories/nadenitsa/1753',
  'https://www.ebag.bg/categories/vurstove/1754',
  'https://www.ebag.bg/categories/pasteti/1755',
  'https://www.ebag.bg/categories/shpekovi-salami/1759',
  'https://www.ebag.bg/categories/lukankovi-salami/1760',
  'https://www.ebag.bg/categories/lukanki/1761',
  'https://www.ebag.bg/categories/sudzhutsi/1762',
  'https://www.ebag.bg/categories/sushenitsa-i-babek/1763',
  'https://www.ebag.bg/categories/italianski-kolbasi/1765',
  'https://www.ebag.bg/categories/ispanski-kolbasi/1766',
  'https://www.ebag.bg/categories/frenski-kolbasi/2167',
  'https://www.ebag.bg/categories/khrvatski-i-ungarski-kolbasi/1767',
  'https://www.ebag.bg/categories/khrvatski-kolbasi/2328',
  'https://www.ebag.bg/categories/kolbasi-ot-berozka/2206',
  'https://www.ebag.bg/categories/svinska-shunka/1769',
  'https://www.ebag.bg/categories/pticha-shunka/1770',
  'https://www.ebag.bg/categories/svinski-fileta-vrat-but-grdi-i-dzholan/1771',
  'https://www.ebag.bg/categories/ptichi-fileta/1772',
  'https://www.ebag.bg/categories/bekon/1773',
  'https://www.ebag.bg/categories/italianski/1775',
  'https://www.ebag.bg/categories/ispanski/1776',
  'https://www.ebag.bg/categories/file-elena-pastrma-i-role/1777',
  'https://www.ebag.bg/categories/zhelirani-mesa/1779',
  'https://www.ebag.bg/categories/sazdrma-i-bakhur/1780',
  'https://www.ebag.bg/categories/bio-khliab-i-khlebni-izdeliia/1882',
  'https://www.ebag.bg/categories/bio-sukhari/1883',
  'https://www.ebag.bg/categories/bio-priasna-pasta/1885',
  'https://www.ebag.bg/categories/bio-plodove/1887',
  'https://www.ebag.bg/categories/bio-zelenchutsi/1888',
  'https://www.ebag.bg/categories/bio-zamrazeni-plodove-i-zelenchutsi/1889',
  'https://www.ebag.bg/categories/bio-surovi-iadki/1890',
  'https://www.ebag.bg/categories/bio-pecheni-iadki/1971',
  'https://www.ebag.bg/categories/bio-susheni-plodove/1891',
  'https://www.ebag.bg/categories/bio-semena/2779',
  'https://www.ebag.bg/categories/bio-priasno-meso/1893',
  'https://www.ebag.bg/categories/bio-vegan-zamestiteli-na-meso/1894',
  'https://www.ebag.bg/categories/bio-kolbasi/1895',
  'https://www.ebag.bg/categories/bio-iaitsa/1896',
  'https://www.ebag.bg/categories/bio-mleka-i-mlechni-napitki/1898',
  'https://www.ebag.bg/categories/bio-sirene-kashkaval-i-izvara/1899',
  'https://www.ebag.bg/categories/bio-vnosni-sirena/1900',
  'https://www.ebag.bg/categories/bio-maslo-i-smetana/1901',
  'https://www.ebag.bg/categories/bio-plodovi-mleka-i-mlechni-deserti/1902',
  'https://www.ebag.bg/categories/bio-iadkovi-soevi-oveseni-i-kokosovi-produkti/1903',
  'https://www.ebag.bg/categories/bio-zakhar-i-podsladiteli/1905',
  'https://www.ebag.bg/categories/bio-brashno-i-maia/1906',
  'https://www.ebag.bg/categories/bio-oriz-variva-zrneni-i-drugi/1907',
  'https://www.ebag.bg/categories/bio-olia-masla-otset-i-limonov-sok/1908',
  'https://www.ebag.bg/categories/bio-pasta-spageti-i-iufka/1909',
  'https://www.ebag.bg/categories/bio-sol-podpravki-i-buloni/1910',
  'https://www.ebag.bg/categories/bio-sladkarski-podpravki/1911',
  'https://www.ebag.bg/categories/bio-med-i-klenov-sirop/1912',
  'https://www.ebag.bg/categories/bio-khranitelni-dobavki/1913',
  'https://www.ebag.bg/categories/bio-tsarevitsa-grakh-fasul-i-nakhut/1915',
  'https://www.ebag.bg/categories/bio-domati/1916',
  'https://www.ebag.bg/categories/bio-liutenitsa/1917',
  'https://www.ebag.bg/categories/bio-maioneza-ketchup-i-sosove/1918',
  'https://www.ebag.bg/categories/bio-maslini/1919',
  'https://www.ebag.bg/categories/bio-khumus-i-pesto/1920',
  'https://www.ebag.bg/categories/bio-sladka-i-konfitiuri/1921',
  'https://www.ebag.bg/categories/bio-shokolad-i-shokoladovi-izdeliia/1926',
  'https://www.ebag.bg/categories/bio-vafli-i-barove/1927',
  'https://www.ebag.bg/categories/bio-biskviti-i-kurabii/1928',
  'https://www.ebag.bg/categories/bio-zakharni-izdeliia/1929',
  'https://www.ebag.bg/categories/bio-snaks-solenki-i-soleti/1930',
  'https://www.ebag.bg/categories/bio-miusli-zrneni-zakuski-i-oveseni-iadki/1931',
  'https://www.ebag.bg/categories/bio-kakaovi-kremove-fstcheno-maslo-i-takhan/1932',
  'https://www.ebag.bg/categories/bio-kafe/802',
  'https://www.ebag.bg/categories/bio-chai/803',
  'https://www.ebag.bg/categories/bio-bezalkokholni-napitki/511',
  'https://www.ebag.bg/categories/bio-alkokholni-napitki/1260',
  'https://www.ebag.bg/categories/adaptirani-mleka/1427',
  'https://www.ebag.bg/categories/kashi/1428',
  'https://www.ebag.bg/categories/piureta/1429',
  'https://www.ebag.bg/categories/bio-detska-pasta/1431',
  'https://www.ebag.bg/categories/bio-biskviti-i-sukhari/1430',
  'https://www.ebag.bg/categories/bio-snaksove/1432',
  'https://www.ebag.bg/categories/bio-sokove/2133',
  'https://www.ebag.bg/categories/bio-kozmetika-za-kosa/1948',
  'https://www.ebag.bg/categories/bio-kozmetika-za-litse/1949',
  'https://www.ebag.bg/categories/bio-dezodoranti-dush-gelove-i-losioni/1950',
  'https://www.ebag.bg/categories/bio-pasta-za-zbi/2777',
  'https://www.ebag.bg/categories/bio-kozmetika-za-rtse-i-kraka/1951',
  'https://www.ebag.bg/categories/bio-sapuni/1952',
  'https://www.ebag.bg/categories/bio-detska-kozmetika/2340',
  'https://www.ebag.bg/categories/bio-perilni-prepaparati/1954',
  'https://www.ebag.bg/categories/bio-pochistvashchi-preparati/1955',
  'https://www.ebag.bg/categories/bio-preparati-za-sdove/1956',
  'https://www.ebag.bg/categories/vegan-zamestiteli-na-meso/2010',
  'https://www.ebag.bg/categories/vegan-zamestiteli-na-kolbasi/2009',
  'https://www.ebag.bg/categories/vegan-zamestiteli-na-mlechni-produkti/2011',
  'https://www.ebag.bg/categories/vegan-sirena/2013',
  'https://www.ebag.bg/categories/vegan-zakvaseni-mleka-i-smetani/2014',
  'https://www.ebag.bg/categories/vegan-masla-i-produkti-za-mazane/2015',
  'https://www.ebag.bg/categories/vegan-smetani/2016',
  'https://www.ebag.bg/categories/vegan-gotveni-iastiia-pitsi-i-supi/2025',
  'https://www.ebag.bg/categories/vegan-sladoled/2028',
  'https://www.ebag.bg/categories/vegan-vafli-biskviti-barove-i-deserti/2026',
  'https://www.ebag.bg/categories/vegan-shokoladi-i-kakaovi-kremove/2027',
  'https://www.ebag.bg/categories/zamrazena-svezha-spirulina/2132',
  'https://www.ebag.bg/categories/khliab-i-khlebni-izdeliia/1975',
  'https://www.ebag.bg/categories/brashno-miksove-i-dobavki-za-pechene/1976',
  'https://www.ebag.bg/categories/pasta/1977',
  'https://www.ebag.bg/categories/biskviti-vafli-i-keikove/1984',
  'https://www.ebag.bg/categories/barove-i-deserti/1978',
  'https://www.ebag.bg/categories/snaks-soleti-i-krekeri/1979',
  'https://www.ebag.bg/categories/zrneni-zakuski-i-oveseni-iadki/1980',
  'https://www.ebag.bg/categories/bira/1981',
  'https://www.ebag.bg/categories/kolbasi/1982',
  'https://www.ebag.bg/categories/drugi/1983',
  'https://www.ebag.bg/categories/mlechni-napitki-i-deserti-bez-zakhar/2030',
  'https://www.ebag.bg/categories/soevi-i-iadkovi-napitki-bez-zakhar/2031',
  'https://www.ebag.bg/categories/sladoledi-i-torti-bez-zakhar/2032',
  'https://www.ebag.bg/categories/bezalkokholni-napitki-i-siropi-bez-zakhar/2033',
  'https://www.ebag.bg/categories/kroasani-i-drugi-pechiva-bez-zakhar/2034',
  'https://www.ebag.bg/categories/barove-i-deserti-bez-zakhar/2035',
  'https://www.ebag.bg/categories/vafli-i-biskiviti-bez-zakhar/2036',
  'https://www.ebag.bg/categories/shokoladi-bonboni-i-kakaovi-kremove-bez-zakhar/2037',
  'https://www.ebag.bg/categories/zrneni-zakuski-i-kornfleiks-bez-zakhar/2038',
  'https://www.ebag.bg/categories/liutenitsa-bez-zakhar/2039',
  'https://www.ebag.bg/categories/konfitiuri-bez-zakhar/2040',
  'https://www.ebag.bg/categories/drugi-produkti-bez-zakhar/2041',
  'https://www.ebag.bg/categories/okhladeni-khrani-s-poveche-protein/2308',
  'https://www.ebag.bg/categories/khliab-s-poveche-protein/2309',
  'https://www.ebag.bg/categories/barcheta-ot-susheno-meso-s-protein/2310',
  'https://www.ebag.bg/categories/deserti-s-poveche-protein/2311',
  'https://www.ebag.bg/categories/kakaovi-kremove-i-sladkishi-s-poveche-protein/2313',
  'https://www.ebag.bg/categories/miusli-i-granola-s-poveche-protein/2314',
  'https://www.ebag.bg/categories/proteinovi-kremove-i-masla/2315',
  'https://www.ebag.bg/categories/soleni-produkti-s-poveche-protein/2316',
  'https://www.ebag.bg/categories/protein-na-prakh/2317',
  'https://www.ebag.bg/categories/proteinova-pasta/2318',
  'https://www.ebag.bg/categories/familni-v-kutiia/2043',
  'https://www.ebag.bg/categories/sladoled-na-klechka/2044',
  'https://www.ebag.bg/categories/sladoled-vv-funiika/2045',
  'https://www.ebag.bg/categories/sladoledeni-kofichki/2046',
  'https://www.ebag.bg/categories/sladoledeni-torti/2047',
  'https://www.ebag.bg/categories/sladoled-bez-zakhar/2048',
  'https://www.ebag.bg/categories/vegan-sladoledi/2099',
  'https://www.ebag.bg/categories/sorbeta/2049',
  'https://www.ebag.bg/categories/dzhelato/2121',
  'https://www.ebag.bg/categories/funiiki-za-sladoled/1969',
  'https://www.ebag.bg/categories/topingi/1985',
  'https://www.ebag.bg/categories/aksesoari-za-sladoled/1848',
  'https://www.ebag.bg/categories/zamrazeni-khliab-pitki-bageti-i-brettseli/2051',
  'https://www.ebag.bg/categories/zamrazeni-banitsi-i-zakuski/2052',
  'https://www.ebag.bg/categories/zamrazeno-testo-i-blatove-za-pitsa/2053',
  'https://www.ebag.bg/categories/zamrazeni-kroasani-i-palachinki/2054',
  'https://www.ebag.bg/categories/zamrazeni-pitsi-lazania-i-drugi/2055',
  'https://www.ebag.bg/categories/brokoli-karfiol-asperzhi-i-briukselsko-zele/2057',
  'https://www.ebag.bg/categories/grakh-fasul-i-edamame/2058',
  'https://www.ebag.bg/categories/spanak-i-zelenolistni/2059',
  'https://www.ebag.bg/categories/tsarevitsa-i-beibi-morkovi/2060',
  'https://www.ebag.bg/categories/chushki-i-bamia/2061',
  'https://www.ebag.bg/categories/zelenchukovi-miksove/2062',
  'https://www.ebag.bg/categories/zamrazeni-podpravki/2063',
  'https://www.ebag.bg/categories/zamrazeni-supi/2064',
  'https://www.ebag.bg/categories/zamrazeni-plodove/2066',
  'https://www.ebag.bg/categories/zamrazeni-plodovi-miksove/2067',
  'https://www.ebag.bg/categories/zamrazeni-plodovi-miksove-za-smuti/2068',
  'https://www.ebag.bg/categories/spirulina/2131',
  'https://www.ebag.bg/categories/zamrazeno-pileshko-meso/2070',
  'https://www.ebag.bg/categories/agneshko-meso/2072',
  'https://www.ebag.bg/categories/zamrazeni-pateshki-subprodukti/2831',
  'https://www.ebag.bg/categories/zamrazeno-su-vid-meso/2071',
  'https://www.ebag.bg/categories/meso-za-giros-i-diuner/2073',
  'https://www.ebag.bg/categories/zamrazeni-mesni-zagotovki/2074',
  'https://www.ebag.bg/categories/zamrazena-riba/2076',
  'https://www.ebag.bg/categories/morski-darove/2077',
  'https://www.ebag.bg/categories/surimi-i-drugi/2079',
  'https://www.ebag.bg/categories/panirani-ribni-produkti/2096',
  'https://www.ebag.bg/categories/panirani-mesni-produkti/2097',
  'https://www.ebag.bg/categories/panirani-bezmesni-khapki/2098',
  'https://www.ebag.bg/categories/zamrazeni-torti-i-sladkishi/2083',
  'https://www.ebag.bg/categories/zamrazeni-donti/2084',
  'https://www.ebag.bg/categories/frenski-makaroni-sufleta-i-deserti/2085',
  'https://www.ebag.bg/categories/brashna-i-maia/2140',
  'https://www.ebag.bg/categories/sol/795',
  'https://www.ebag.bg/categories/spetsialni-podpravki/985',
  'https://www.ebag.bg/categories/osnovni-podpravki/398',
  'https://www.ebag.bg/categories/podpravki-smesi/399',
  'https://www.ebag.bg/categories/listni-podpravki/796',
  'https://www.ebag.bg/categories/melnichki-i-solnitsi/792',
  'https://www.ebag.bg/categories/zekhtin/413',
  'https://www.ebag.bg/categories/olio/629',
  'https://www.ebag.bg/categories/otset/389',
  'https://www.ebag.bg/categories/balsamov-otset/791',
  'https://www.ebag.bg/categories/drugi-masla/1529',
  'https://www.ebag.bg/categories/oriz/284',
  'https://www.ebag.bg/categories/bob/287',
  'https://www.ebag.bg/categories/leshcha/285',
  'https://www.ebag.bg/categories/drugi-variva/286',
  'https://www.ebag.bg/categories/domateni-piureta-i-sosove/358',
  'https://www.ebag.bg/categories/liutenitsa/350',
  'https://www.ebag.bg/categories/krastavichki-konservi/355',
  'https://www.ebag.bg/categories/tsarevitsa-konservi/351',
  'https://www.ebag.bg/categories/gbi-konservi/359',
  'https://www.ebag.bg/categories/grakh-konservi/360',
  'https://www.ebag.bg/categories/bob-i-fasul-konservi/361',
  'https://www.ebag.bg/categories/kapiia-i-chushki-konservi/356',
  'https://www.ebag.bg/categories/mesni-konservi/354',
  'https://www.ebag.bg/categories/ribni-konservi/352',
  'https://www.ebag.bg/categories/plodovi-konservi/876',
  'https://www.ebag.bg/categories/drugi-konservi/357',
  'https://www.ebag.bg/categories/maslini-nasipni/367',
  'https://www.ebag.bg/categories/maslini-v-burkan-i-vakuum/368',
  'https://www.ebag.bg/categories/zeleni-maslini-v-burkan-i-vakuum/1967',
  'https://www.ebag.bg/categories/maslinova-pasta/822',
  'https://www.ebag.bg/categories/sosove-za-pasta/2002',
  'https://www.ebag.bg/categories/sosove-pesto/453',
  'https://www.ebag.bg/categories/ketchup/457',
  'https://www.ebag.bg/categories/maioneza/455',
  'https://www.ebag.bg/categories/gorchitsa/458',
  'https://www.ebag.bg/categories/limonov-sok/456',
  'https://www.ebag.bg/categories/sosove-soevi/452',
  'https://www.ebag.bg/categories/spetsialni-sosove-i-dresingi/639',
  'https://www.ebag.bg/categories/supi/401',
  'https://www.ebag.bg/categories/fiksove/400',
  'https://www.ebag.bg/categories/prakhoobrazni-smesi/320',
  'https://www.ebag.bg/categories/pasta-i-makaroni/366',
  'https://www.ebag.bg/categories/spageti-i-lazania/364',
  'https://www.ebag.bg/categories/lazania/1124',
  'https://www.ebag.bg/categories/fide-iufka-i-kuskus/1445',
  'https://www.ebag.bg/categories/polugotovi/365',
  'https://www.ebag.bg/categories/techen-shokolad-i-toping/311',
  'https://www.ebag.bg/categories/takhan-i-fstcheno-maslo/846',
  'https://www.ebag.bg/categories/med/349',
  'https://www.ebag.bg/categories/sladka/353',
  'https://www.ebag.bg/categories/toping/1958',
  'https://www.ebag.bg/categories/barove-i-deserti-novo/2111',
  'https://www.ebag.bg/categories/shokolad/2319',
  'https://www.ebag.bg/categories/bonbonieri-novo/2855',
  'https://www.ebag.bg/categories/bonboni-dvki-drazheta-i-zhelirani-bonboni-novo/2297',
  'https://www.ebag.bg/categories/mochi/2805',
  'https://www.ebag.bg/categories/biskviti/325',
  'https://www.ebag.bg/categories/vafli-novo/2342',
  'https://www.ebag.bg/categories/khalva-i-lokum/308',
  'https://www.ebag.bg/categories/kornfleiks/314',
  'https://www.ebag.bg/categories/miusli/309',
  'https://www.ebag.bg/categories/zrneni-zakuski/315',
  'https://www.ebag.bg/categories/granola/1757',
  'https://www.ebag.bg/categories/oveseni-iadki-i-tritsi/872',
  'https://www.ebag.bg/categories/chips/445',
  'https://www.ebag.bg/categories/snaks/450',
  'https://www.ebag.bg/categories/brusketi/770',
  'https://www.ebag.bg/categories/soleni-biskviti/324',
  'https://www.ebag.bg/categories/soleti/449',
  'https://www.ebag.bg/categories/pukanki/451',
  'https://www.ebag.bg/categories/snaks-ot-susheno-meso/1804',
  'https://www.ebag.bg/categories/specialty-coffee/2142',
  'https://www.ebag.bg/categories/kafe-na-zrna/327',
  'https://www.ebag.bg/categories/kafe-mliano/328',
  'https://www.ebag.bg/categories/kafe-na-kapsuli-n/2104',
  'https://www.ebag.bg/categories/kafe-instantno/329',
  'https://www.ebag.bg/categories/kafe-bez-kofein/1853',
  'https://www.ebag.bg/categories/kafe-miksove/1854',
  'https://www.ebag.bg/categories/napitki-s-kafe/552',
  'https://www.ebag.bg/categories/zamestiteli-na-kafe/1966',
  'https://www.ebag.bg/categories/sukho-mliako-i-smetana/839',
  'https://www.ebag.bg/categories/iadlivi-chashi-za-kafe/1841',
  'https://www.ebag.bg/categories/chai-novo/2122',
  'https://www.ebag.bg/categories/goreshch-shokolad/1850',
  'https://www.ebag.bg/categories/kakao/1851',
  'https://www.ebag.bg/categories/aksesoari-za-topli-napitki/1852',
  'https://www.ebag.bg/categories/alkalna-voda/1146',
  'https://www.ebag.bg/categories/mineralna-voda/566',
  'https://www.ebag.bg/categories/izvorna-voda/567',
  'https://www.ebag.bg/categories/trapezna-voda/569',
  'https://www.ebag.bg/categories/gazirana-voda/568',
  'https://www.ebag.bg/categories/gazirani-napitki-bez-zakhar/2120',
  'https://www.ebag.bg/categories/gazirani-napitki-novo/2780',
  'https://www.ebag.bg/categories/studen-chai/267',
  'https://www.ebag.bg/categories/kombucha/2785',
  'https://www.ebag.bg/categories/kafe-napitki/2786',
  'https://www.ebag.bg/categories/100-sok/2787',
  'https://www.ebag.bg/categories/nektari/2788',
  'https://www.ebag.bg/categories/negazirani-napitki/270',
  'https://www.ebag.bg/categories/napitki-s-aloe-vera/551',
  'https://www.ebag.bg/categories/smutita/949',
  'https://www.ebag.bg/categories/novo-sokove-i-nektari-v-malka-razfasovka/2796',
  'https://www.ebag.bg/categories/siropi/1139',
  'https://www.ebag.bg/categories/shotove/2795',
  'https://www.ebag.bg/categories/energiini-napitki/1786',
  'https://www.ebag.bg/categories/vitaminni-napitki/829',
  'https://www.ebag.bg/categories/lager/2816',
  'https://www.ebag.bg/categories/eil/2817',
  'https://www.ebag.bg/categories/kraft-biri/1453',
  'https://www.ebag.bg/categories/bezalkokholna-bira/1546',
  'https://www.ebag.bg/categories/spetsialni-biri/2818',
  'https://www.ebag.bg/categories/bira-bez-gluten/2819',
  'https://www.ebag.bg/categories/niskoalkokholno-vino/1263',
  'https://www.ebag.bg/categories/bialo-vino/562',
  'https://www.ebag.bg/categories/cherveno-vino/563',
  'https://www.ebag.bg/categories/roze/564',
  'https://www.ebag.bg/categories/bag-in-box-3-l/818',
  'https://www.ebag.bg/categories/penlivo-vino/565',
  'https://www.ebag.bg/categories/bezalkokholno-vino-i-penlivo-vino/1972',
  'https://www.ebag.bg/categories/chashi-i-aksesoari-za-vino/1970',
  'https://www.ebag.bg/categories/premium-selektsiia-alkokhol/2135',
  'https://www.ebag.bg/categories/spetsialni-komplekti/1106',
  'https://www.ebag.bg/categories/vodka/553',
  'https://www.ebag.bg/categories/uiski-i-brbn/554',
  'https://www.ebag.bg/categories/dzhin/555',
  'https://www.ebag.bg/categories/rom/556',
  'https://www.ebag.bg/categories/koniak-i-brendi/557',
  'https://www.ebag.bg/categories/anasonovi-napitki/559',
  'https://www.ebag.bg/categories/tekila/560',
  'https://www.ebag.bg/categories/rakiia/561',
  'https://www.ebag.bg/categories/bezalkokholen-dzhin-i-rom/1973',
  'https://www.ebag.bg/categories/saider/1964',
  'https://www.ebag.bg/categories/kokteili-i-miksove/1965',
  'https://www.ebag.bg/categories/radler/2830',
  'https://www.ebag.bg/categories/adaptirani-mleka/291',
  'https://www.ebag.bg/categories/kashi/293',
  'https://www.ebag.bg/categories/piureta-novo/2807',
  'https://www.ebag.bg/categories/sukhari-bishkoti-i-biskviti/841',
  'https://www.ebag.bg/categories/voda-sokove-i-chai/1537',
  'https://www.ebag.bg/categories/peleni-novo/2832',
  'https://www.ebag.bg/categories/gashchichki-novo/2843',
  'https://www.ebag.bg/categories/biorazgradimi-peleni/2094',
  'https://www.ebag.bg/categories/gashchichki-za-pluvane/2093',
  'https://www.ebag.bg/categories/vlazhni-krpichki/428',
  'https://www.ebag.bg/categories/antibakterialni-krpi/2087',
  'https://www.ebag.bg/categories/biorazgradimi-krpi/2088',
  'https://www.ebag.bg/categories/krpi-s-voda/2089',
  'https://www.ebag.bg/categories/vlazhna-toaletna-khartiia/2090',
  'https://www.ebag.bg/categories/shampoan-i-dush-gel/858',
  'https://www.ebag.bg/categories/za-zbi/856',
  'https://www.ebag.bg/categories/losion-i-krem-za-tialo/859',
  'https://www.ebag.bg/categories/sapun/857',
  'https://www.ebag.bg/categories/perilni-preparati/1548',
  'https://www.ebag.bg/categories/detski-omekotiteli/1549',
  'https://www.ebag.bg/categories/preparati-protiv-petna/1550',
  'https://www.ebag.bg/categories/izmivane-na-sdove-i-pochistvane/1551',
  'https://www.ebag.bg/categories/shisheta-i-chashi/1542',
  'https://www.ebag.bg/categories/zalgalki/1543',
  'https://www.ebag.bg/categories/khranene/1544',
  'https://www.ebag.bg/categories/drugi-prinadlezhnosti/1545',
  'https://www.ebag.bg/categories/obrazovatelni-i-nastolni-igri/1566',
  'https://www.ebag.bg/categories/aktivni-karti-i-knizhki/1568',
  'https://www.ebag.bg/categories/igrachki/1565',
  'https://www.ebag.bg/categories/dush-gelove/2153',
  'https://www.ebag.bg/categories/sapuni/2154',
  'https://www.ebag.bg/categories/piling-i-skrab-za-tialo/2155',
  'https://www.ebag.bg/categories/soli-i-piana-za-vana/2156',
  'https://www.ebag.bg/categories/bio-dush-gelove/2157',
  'https://www.ebag.bg/categories/bio-sapuni/2158',
  'https://www.ebag.bg/categories/masazhori-gbi-i-shapki-za-bania/2159',
  'https://www.ebag.bg/categories/pasta-za-zbi-novo/2170',
  'https://www.ebag.bg/categories/chenki-za-zbi-novo/2171',
  'https://www.ebag.bg/categories/voda-za-usta-novo/2172',
  'https://www.ebag.bg/categories/interdentalno-pochistvane/2173',
  'https://www.ebag.bg/categories/kontsi-za-zbi/854',
  'https://www.ebag.bg/categories/bio-pasti-za-zbi/2175',
  'https://www.ebag.bg/categories/damski-prevrzki/427',
  'https://www.ebag.bg/categories/ezhednevni-damski-prevrzki/810',
  'https://www.ebag.bg/categories/damski-tamponi/809',
  'https://www.ebag.bg/categories/damski-dezodoranti-novo/2186',
  'https://www.ebag.bg/categories/damski-dush-gelove/2190',
  'https://www.ebag.bg/categories/intimna-kozmetika/726',
  'https://www.ebag.bg/categories/damsko-brsnene-i-depilatsiia/2191',
  'https://www.ebag.bg/categories/meditsinski-peleni-i-prevrzki/2192',
  'https://www.ebag.bg/categories/kremove/338',
  'https://www.ebag.bg/categories/maski/844',
  'https://www.ebag.bg/categories/pochistvashchi-produkti-za-litse/2196',
  'https://www.ebag.bg/categories/balsam-za-ustni/2341',
  'https://www.ebag.bg/categories/produkti-ot-pamuk/2202',
  'https://www.ebag.bg/categories/bio-kozmetika-za-litse/2205',
  'https://www.ebag.bg/categories/boia-za-kosa/836',
  'https://www.ebag.bg/categories/shampoan/2208',
  'https://www.ebag.bg/categories/balsami-sa-kosa/2209',
  'https://www.ebag.bg/categories/maski-olia-i-serumi-za-kosa/2210',
  'https://www.ebag.bg/categories/stilizanti-za-kosa/2211',
  'https://www.ebag.bg/categories/bio-kozmetika-za-kosa/2212',
  'https://www.ebag.bg/categories/losioni-i-kremove-za-tialo/2223',
  'https://www.ebag.bg/categories/universalni-kremove/2224',
  'https://www.ebag.bg/categories/avtobronzanti/2225',
  'https://www.ebag.bg/categories/grizha-za-rtse-i-nokti/2226',
  'https://www.ebag.bg/categories/grizha-za-kraka/2227',
  'https://www.ebag.bg/categories/antitselulitni-produkti/2228',
  'https://www.ebag.bg/categories/masazhori-gbi-i-shapki-za-bania/2229',
  'https://www.ebag.bg/categories/vlazhni-krpichki-i-dezinfektanti/2230',
  'https://www.ebag.bg/categories/slntsezashchita-i-repelenti/2231',
  'https://www.ebag.bg/categories/bio-kozmetika-za-tialo/2232',
  'https://www.ebag.bg/categories/damski-dezodoranti-sprei/2246',
  'https://www.ebag.bg/categories/damski-dezodoranti-rol-on/2247',
  'https://www.ebag.bg/categories/damski-dezodoranti-stik/2248',
  'https://www.ebag.bg/categories/mzhki-dezodoranti-sprei/2249',
  'https://www.ebag.bg/categories/mzhki-dezodoranti-rol-on/2250',
  'https://www.ebag.bg/categories/mzhki-dezodoranti-stik/2251',
  'https://www.ebag.bg/categories/bio-dezodoranti/2252',
  'https://www.ebag.bg/categories/depilirashchi-produkti/2254',
  'https://www.ebag.bg/categories/damski-nozhcheta-i-samobrsnachki/2255',
  'https://www.ebag.bg/categories/piana-i-gel-za-brsnene/2256',
  'https://www.ebag.bg/categories/mzhki-nozhcheta-i-samobrsnachki/2257',
  'https://www.ebag.bg/categories/produkti-za-sled-brsnene/2258',
  'https://www.ebag.bg/categories/grizha-za-litse/2260',
  'https://www.ebag.bg/categories/produkti-za-brada/1750',
  'https://www.ebag.bg/categories/dush-gel-za-mzhe/2261',
  'https://www.ebag.bg/categories/samobrsnachki-i-nozhcheta/336',
  'https://www.ebag.bg/categories/piana-gel-za-brsnene/820',
  'https://www.ebag.bg/categories/aftrsheiv/819',
  'https://www.ebag.bg/categories/mzhki-dezodoranti-novo/2263',
  'https://www.ebag.bg/categories/shampoani-za-mzhe/2262',
  'https://www.ebag.bg/categories/damski-podarchni-komplekti/2268',
  'https://www.ebag.bg/categories/mzhki-podarchni-komplekti/2269',
  'https://www.ebag.bg/categories/predpazni-maski-novo/2271',
  'https://www.ebag.bg/categories/dezinfektanti-novo/2272',
  'https://www.ebag.bg/categories/za-vasheto-zdrave-novo/2273',
  'https://www.ebag.bg/categories/za-intimnite-momenti/2274',
  'https://www.ebag.bg/categories/pamuchni-produkti-i-konsumativi/2275',
  'https://www.ebag.bg/categories/sanitarni/2276',
  'https://www.ebag.bg/categories/chetki-grebeni-i-rolki/2286',
  'https://www.ebag.bg/categories/nozhichki/2287',
  'https://www.ebag.bg/categories/pinseti/2288',
  'https://www.ebag.bg/categories/shnoli-fibi-i-lastitsi/2289',
  'https://www.ebag.bg/categories/pili/2290',
  'https://www.ebag.bg/categories/noktorezachki/2291',
  'https://www.ebag.bg/categories/toaletna-khartiia/421',
  'https://www.ebag.bg/categories/vlazhna-toaletna-khartiia/2334',
  'https://www.ebag.bg/categories/kukhnenski-rula/426',
  'https://www.ebag.bg/categories/salfetki/422',
  'https://www.ebag.bg/categories/krpi-v-kutiia/297',
  'https://www.ebag.bg/categories/nosni-krpi/425',
  'https://www.ebag.bg/categories/aromatizatori-za-wc/283',
  'https://www.ebag.bg/categories/za-bania-i-toaletna/689',
  'https://www.ebag.bg/categories/universalni/687',
  'https://www.ebag.bg/categories/za-kukhnia/688',
  'https://www.ebag.bg/categories/preparat-za-pod/686',
  'https://www.ebag.bg/categories/za-mebeli/2335',
  'https://www.ebag.bg/categories/preparat-za-stklo/852',
  'https://www.ebag.bg/categories/drugi-preparati/685',
  'https://www.ebag.bg/categories/mokri-krpi-za-domakinstvoto/2337',
  'https://www.ebag.bg/categories/gel-za-prane/397',
  'https://www.ebag.bg/categories/kapsuli-za-prane/396',
  'https://www.ebag.bg/categories/prakh-za-prane/394',
  'https://www.ebag.bg/categories/omekotiteli/531',
  'https://www.ebag.bg/categories/perilni-drugi/395',
  'https://www.ebag.bg/categories/omekotiteli-na-vodata/2338',
  'https://www.ebag.bg/categories/tabletki-za-sdomiialna/691',
  'https://www.ebag.bg/categories/gel-za-sdomiialna/692',
  'https://www.ebag.bg/categories/techni-preparati-za-sdove/278',
  'https://www.ebag.bg/categories/drugi-za-sdomiialna/853',
  'https://www.ebag.bg/categories/folio-i-khartiia-za-pechene/1248',
  'https://www.ebag.bg/categories/torbi-za-smet/1201',
  'https://www.ebag.bg/categories/aromatizatori-za-vzdukh-novo/2356',
  'https://www.ebag.bg/categories/sveshchi/1128',
  'https://www.ebag.bg/categories/baterii/409',
  'https://www.ebag.bg/categories/elektricheski-krushki/407',
  'https://www.ebag.bg/categories/plikove-za-khrana-i-plikove-led/466',
  'https://www.ebag.bg/categories/mrezha-za-prane/1202',
  'https://www.ebag.bg/categories/drugi/1207',
  'https://www.ebag.bg/categories/filtrirashchi-kani/1166',
  'https://www.ebag.bg/categories/nozhove/1011',
  'https://www.ebag.bg/categories/chinii-chashi-kani-i-kupi/1009',
  'https://www.ebag.bg/categories/tavi-tigani-i-tendzheri/1010',
  'https://www.ebag.bg/categories/tirbushoni-i-belachki/1227',
  'https://www.ebag.bg/categories/sdove-za-skhranenie/1007',
  'https://www.ebag.bg/categories/formi-za-sladki-i-pechiva/1295',
  'https://www.ebag.bg/categories/domakinski-rkavitsi/1021',
  'https://www.ebag.bg/categories/domakinski-gbi/461',
  'https://www.ebag.bg/categories/popivatelni-krpi/299',
  'https://www.ebag.bg/categories/domakinska-tel/464',
  'https://www.ebag.bg/categories/pochistvashchi-i-mikrofibrni-krpi/788',
  'https://www.ebag.bg/categories/mop-chetki-i-podochistachki/789',
  'https://www.ebag.bg/categories/khavliena-krpa/1186',
  'https://www.ebag.bg/categories/tekstil-za-kukhnia/1249',
  'https://www.ebag.bg/categories/tekstil-za-spalnia/1250',
  'https://www.ebag.bg/categories/chorapi/1015',
  'https://www.ebag.bg/categories/chorapogashchi/1016',
  'https://www.ebag.bg/categories/chadri/1562',
  'https://www.ebag.bg/categories/semena/1572',
  'https://www.ebag.bg/categories/torove-i-pochvi/1573',
  'https://www.ebag.bg/categories/saksii-i-instrumenti/1574',
  'https://www.ebag.bg/categories/barbekiu/1129',
  'https://www.ebag.bg/categories/parti/1184',
  'https://www.ebag.bg/categories/boia-za-obuvki/1577',
  'https://www.ebag.bg/categories/gbi-za-obuvki/1579',
  'https://www.ebag.bg/categories/sprei-i-vlazhni-krpi/1580',
  'https://www.ebag.bg/categories/aksesoari-za-obuvki/1581',
  'https://www.ebag.bg/categories/ofis/1262',
  'https://www.ebag.bg/categories/novo-knizharnitsa/1062',
  'https://www.ebag.bg/categories/elektronika-i-mobilni-telefoni/1157',
  'https://www.ebag.bg/categories/sukha-khrana/861',
  'https://www.ebag.bg/categories/konservi/862',
  'https://www.ebag.bg/categories/pauch/869',
  'https://www.ebag.bg/categories/lakomstva/863',
  'https://www.ebag.bg/categories/aksesoari/1215',
  'https://www.ebag.bg/categories/kozmetika/1231',
  'https://www.ebag.bg/categories/sukha-khrana/864',
  'https://www.ebag.bg/categories/khapki-v-sos-i-pauch/865',
  'https://www.ebag.bg/categories/pastet-i-konservi/866',
  'https://www.ebag.bg/categories/lakomstva/867',
  'https://www.ebag.bg/categories/koteshka-treva-i-maltsova-pasta/2803',
  'https://www.ebag.bg/categories/koteshka-toaletna/868',
  'https://www.ebag.bg/categories/aksesoari/1229',
  'https://www.ebag.bg/categories/kozmetika/1232',
];

const scrape = async (url, page, products) => {
  await page.goto(url);

  await page.evaluate(async () => {
    let scrollHeight = 0;

    while (document.documentElement.scrollHeight > scrollHeight) {
      scrollHeight = document.documentElement.scrollHeight;
      window.scrollBy(0, scrollHeight);

      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  });

  const elements = await page.$$('article.item');

  for (const element of elements) {
    const title = await element.$('h2');
    const titleValue = await title.evaluate((el) => el.textContent);

    const productUrl = await title.$eval('a', (el) => el.href);
    const description = await element.$('p.product-expiry-date');
    let descriptionValue = '';
    if (description) {
      descriptionValue = await description.evaluate((el) => el.textContent);
    }

    const images = await element.$$eval('img', (imgs) => {
      return imgs.map((x) => x.src);
    });

    const imageUrl = images[0];
    const newPrice = await element.$('p.new-price');
    let priceValue = 0.0;
    if (newPrice) {
      priceValue = await newPrice.evaluate((el) => el.textContent);
    } else {
      const price = await element.$('p.product-price');
      priceValue = await price.evaluate((el) => el.textContent);
    }

    const unit = await element.$('.price-per-kg');
    let unitValue = '';
    if (unit) {
      unitValue = await unit.evaluate((el) => el.textContent);
    }

    products.push({
      title: titleValue,
      description: descriptionValue,
      imageUrl,
      price: priceValue,
      unit: unitValue,
      productUrl
    });
  }
};

(async () => {
  try {
    const browser = await puppeteer.launch({
      headless: 'new', // Run the browser with a visible UI
      protocolTimeout: 4_000_000, // > 1 hr
    });
    const page = await browser.newPage();

    const products = [];
    for (const url of urlsToScrape) {
      await scrape(url, page, products);
    }

    parentPort.postMessage({
      result: products,
      locations: [
        {
          country: "Bulgaria",
          city: "Plovdiv",
          isPhysical: false,
        },
        {
          country: "Bulgaria",
          city:"Sofia",
          isPhysical: false,
        },
        {
          country: "Bulgaria",
          city:"Pernik",
          isPhysical: false,
        },
        {
          country: "Bulgaria",
          city:"Dupnica",
          isPhysical: false,
        },
        {
          country: "Bulgaria",
          city:"Blagoevgrad",
          isPhysical: false,
        },
        {
          country: "Bulgaria",
          city:"Bansko",
          isPhysical: false,
        },
        {
          country: "Bulgaria",
          city:"Pazardzhik",
          isPhysical: false,
        },
        {
          country: "Bulgaria",
          city:"Asenovgrad",
          isPhysical: false,
        }
      ],
    });
  }
  catch(err) {
      parentPort.postMessage({ error: err });
  }
  finally {
      await browser.close();
      process.exit(0);
  }
})();
