apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: botbotov/ai
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ai-srv
spec:
  selector:
    app: ai
  ports:
    - name: ai
      protocol: TCP
      port: 3000
      targetPort: 3000
