apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - shopsmart.dev
      secretName: ingress-tls-secret
  rules:
    - host: shopsmart.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/main/?(.*)
            pathType: Prefix
            backend:
              service:
                name: main-srv
                port:
                  number: 3000
          - path: /api/stats/?(.*)
            pathType: Prefix
            backend:
              service:
                name: stats-srv
                port:
                  number: 3000
          - path: /api/ai/?(.*)
            pathType: Prefix
            backend:
              service:
                name: ai-srv
                port:
                  number: 3000
